version: "3.9"

services:
  db:
    image: postgres:17
    container_name: pubkviz-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pubkviz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: pubkviz-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pubkviz
    ports:
      - "3000:3000"
    command: sh -c "npm run db:migrate && npm run db:seed && npm start"

volumes:
  postgres_data: